// This file is generated by Astro DB
declare module 'astro:db' {
	export const VoteSelections: import("@astrojs/db/runtime").Table<
		"VoteSelections",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"VoteSelections","primaryKey":true}}}
	>;
	export const Votes: import("@astrojs/db/runtime").Table<
		"Votes",
		{"id":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Votes","primaryKey":true}},"combatId":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"combatId","collection":"Votes","primaryKey":false,"optional":false}},"userId":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"userId","collection":"Votes","primaryKey":false,"optional":false}},"voteId":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"voteId","collection":"Votes","primaryKey":false,"optional":false,"references":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"id","collection":"VoteSelections","primaryKey":true}}}},"votedAt":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"votedAt","collection":"Votes"}}}
	>;
}
